### ISSUE TITLE
got compile error ../src/es/unizar/pproc/vocabulary/S.java:50: error: package ORG does not exist 

### ISSUE THREAD

**Issue by richhl** [gesteban/pproc-pcsp#1]
To reproduce in a debian environment:

$> git clone https://github.com/gesteban/pproc-pcsp
$> cd pproc-pcsp/Project/src
$> find .. -name "*.java" -exec javac -cp "../lib/*"  \{\} \;

I got ../src/es/unizar/pproc/vocabulary/S.java:50: error: package ORG does not exist
		public static final Node Organization = ORG.Organization.asNode();
		                                           ^
../src/es/unizar/pproc/vocabulary/S.java:51: error: package ORG does not exist
		public static final Node hasSite = ORG.hasSite.asNode();

missing library?

**Comment by gesteban** [comment]
Caused by some not needed old code lines.
Fixed at 774e32c6af4934b7ed0a31d056582d5c91eebbfb.
